pre-commit:
  jobs:
    - name: prettier
      run: npx --no-install prettier --check .
    - name: uv
      run: uv lock --check

commit-msg:
  jobs:
    - name: commitlint
      only:
        - ref: main
      run: npx --no-install commitlint --edit "{1}"
