pre-commit:
  jobs:
    - name: prettier
      run: npx --no-install prettier --check .
    - name: uv
      run: uv lock --check
    - name: ruff
      env:
        UV_NO_SYNC: "true"
      group:
        jobs:
          - name: check
            run: uv run ruff check .
          - name: format
            run: uv run ruff format --diff .
    - name: mypy
      run: uv run mypy .

commit-msg:
  jobs:
    - name: commitlint
      only:
        - ref: main
      run: npx --no-install commitlint --edit "{1}"
